# Generated by Django 3.2.13 on 2022-06-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Saiu p entrega', 'Saiu p entrega'), ('Entregue', 'Entregue')], max_length=200, null=True)),
                ('date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_Created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
