# Generated by Django 4.0.5 on 2022-06-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_order_tagas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tagas',
            new_name='tags',
        ),
    ]
