# Generated by Django 3.2.13 on 2022-06-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_Created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_Created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='date_Created',
            new_name='date_created',
        ),
    ]
